import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Banner } from "../components/Banner/Banner";
import { Navbar } from "../components/Navbar/Navbar";
import { Card } from "../components/Card/Card";
import { SectionCards } from "../components/Card/SectionCards";
import { getVideos } from "../lib/videos";

export default function Home() {
  const disneyVideos = getVideos()
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="test@test.com" />

      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/clifford.webp"
      />

      <div className={styles.sectionWrapper}></div>
      <SectionCards title="Disney" videos={disneyVideos} size="large" />
      <SectionCards title="Productivity" videos={disneyVideos} size="medium" />
    </div>
  );
}
